services:
  - type: web
    name: datuxdesignweb
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: node ./dist/server/entry.mjs
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
    plan: starter
    autoDeploy: true

staticPublishPath: ./dist
headers:
  - path: /styles/main.css
    name: Cache-Control
    value: public, max-age=31536000, immutable